export interface User {
  ID: number,
  PARENT_ID: number,
  TYPE: string,
  NAME: string,
  DESCRIPTION: string,
  POS: string,
  TABID: string,
  STATUS: string,
  CODEKEY: string,
  CODEKEYTIME:string,
  CODEKEY_DISP_FORMAT: string,
  SOAA_KEY_STATUS:string,
  SOAA_UID:string,
  EXPTIME:string,
  CREATEDTIME: Date,
  FIREDTIME:string,
  BADGE:string,
  BADGEB:string,
  BOOLPARAM1:string,
  BOOLPARAM2:string,
  BOOLPARAM3:string,
  BOOLPARAM4:string,
  LOCATIONZONE:string,
  LOCATIONACT:string,
  APB_ON:string,
  SIDEPARAM0:string,
  SIDEPARAM1:string,
  SIDEPARAM2:string,
  SIDEPARAM3:string,
  SIDEPARAM4:string,
  SIDEPARAM5:string,
  NTFY_PASS_ENABLED:string,
  SMS_TARGETNUMBER:string,
  NTFY_STARTDATE:string,
  NTFY_ENDDATE:string,
  NTFY_PASS_TEXT:string,
  NTFY_PAY_ENABLED:string,
  NTFY_PAY_TEXT:string,
  NTFY_LAST_TIME:string,
  NTFY_LAST_AP:string,
  NTFY_LAST_DIR:string,
  NTFY_LAST_SENT:string,
  LASTPASS_AP:string,
  AD_ENABLED:string,
  AD_DOMAIN_ID:string,
  AD_USER_DN:string,
  AD_SYNC_PENDING:string,
  EXTSOURCEID:string,
  EXTID:string,
  USER_ENABLED:string,
  USER_LOGIN:string,
  USER_PASSWORD:string,
  USER_GSTAPPL_RANGE:string,
  USER_GSTAPPL_CREATE:string,
  USER_GSTAPPL_MODIFY:string,
  USER_DEPSRESTRICTION:string,
  USER_MONVIEW_POLICY:string,
  USER_APRESTRICTION:string,
  USER_FLOORSRESTRICTION:string,
  USER_REPRESTRICTION:string,
  USER_EXITPASSWORD:string,
  USER_EXITPASSWORD_USED:string,
  USER_T_EDITPLANS:string,
  USER_T_CARDLOGIN:string,
  USER_CHOWNPASS:string,
  USER_WRITEDB:string,
  USER_T_HW:string,
  USER_T_MON:string,
  USER_T_MON_CNTLAP:string,
  USER_T_MON_ALLOWANONPASS:string,
  USER_T_MON_ALLOWPASS:string,
  USER_T_MON_ALLOWAUTHPASS:string,
  USER_T_PAYACC:string,
  USER_T_PERSONAL:string,
  USER_T_PERSONAL_EDIT:string,
  USER_T_PERSONAL_BADGES:string,
  USER_T_PERSONAL_ACC:string,
  USER_T_PERSONAL_SMS:string,
  USER_T_PERSONAL_ACCESS:string,
  USER_T_PERSONAL_SETZONE:string,
  USER_T_PAYINC:string,
  USER_T_PAYDESK:string,
  USER_T_PAYDESK_ACCINC:string,
  USER_T_PAYDESK_MANUALSELECT:string,
  USER_T_PAYDESKLITE:string,
  USER_T_PAYDESKLITE_MANUALSEL:string,
  USER_T_RULES: string,
  USER_T_PAYMENU: string,
  USER_T_AUTOPARK: string,
  USER_T_GUESTS: string,
  USER_T_GUESTS_EDIT: string,
  USER_T_GUESTS_DELETEPD: string,
  USER_T_EVENTS: string,
  USER_T_ALARM: string,
  USER_T_ALARM_EDITCONF: string,
  USER_T_ARCHIVE: string,
  USER_T_REPORTS: string,
  USER_T_USERS: string,
  USER_LOCALSETTINGS: string,
  USER_T_PLANS: string,
  USER_CNTLMODULES: string,
  USER_T_OD: string,
  USER_T_PARKINGTARIFFS: string,
  USER_T_PARKINGPAY: string,
  USER_OIF: string,
  LASTLPR_AP: string,
  LASTLPR_DIR: string,
  LASTLPR_TIME:string,
  MF_UID:string,
  NTFY_TYPE:string,
  USER_T_NFCTERMINAL: string,
  USER_T_NFCTERMINAL_REG_IN: string,
  USER_T_NFCTERMINAL_REG_OUT: string,
  USER_T_NFCTERMINAL_REG_AUTO: string,
  NTFY_PAY_DEC_ENABLED: string,
  NTFY_PAY_DEC_TEXT: string,
  NTFY_PAY_DEC_THR: string,
  USER_T_PERSONAL_ADD: string,
  USER_T_PERSONAL_DEL: string,
  USER_T_PAYACCMNG: string,
  EMAIL: string,
  EMAIL_SUBJECT: string,
  TELEGRAM_CHATID: string,
  USER_ALMRESTRICTION: string,
  APL_ON: string,
  APL_EXPTIME:string,
  USER_T_ALARM_CMD:string,
  USER_T_FACE:string,
  NTFY_GSTAPPL_ENABLED:string,
  NTFY_GSTAPPL_TEXT:string,
  USER_APPLS_SEE_CURRENT:string,
  USER_APPLS_SEE_ALL:string,
  USER_APPLS_EDIT_CURRENT:string,
  USER_APPLS_EDIT_ALL:string
}